baseurl = "https://fakorede.github.io/"
title = "Home"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Fakorede Abiola"
    description = "Fakorede Abiola's personal website"
    keywords = "blog,developer,personal"
    info = "Backend Developer"
    avatarurl = "images/avatar.jpg"
    #gravatar = "john.doe@example.com"
    #footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = true
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/fakorede/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/thefabdev/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/fakorede/"
[[params.social]]
    name = "Medium"
    icon = "fas fa-globe"
    weight = 5
    url = "https://fabcodes.hashnode.dev/"
[[params.social]]
    name = "Stack Overflow"
    icon = "fab fa-stack-overflow"
    weight = 6
    url = "https://stackoverflow.com/users/6883910/abiola"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "ğŸ‘¦ğŸ½About me"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "ğŸ“–Blog"
            weight = 2
            url = "https://fabcodes.hashnode.dev/"

            [[languages.en.menu.main]]
            name = "ğŸ‘¨â€ğŸ’»Work"
            weight = 3
            url = "work/"

            [[languages.en.menu.main]]
            name = "ğŸ“²Contact me"
            weight = 4
            url = "mailto:abiolafakorede@gmail.com"

            [[languages.en.menu.main]]
            name = "ğŸ“Resume"
            weight = 5
            url = "https://drive.google.com/file/d/1HsyYHujlBLpsqL5LYcllm4eZ3eVfObEl/view?usp=sharing"
